import Head from "next/head";
import Collage from "../components/Collage";
import Hero from "../components/Hero";
import HeroTwo from "../components/HeroTwo";
import Navbar from "../components/Navbar";
import Modal from "@mui/material/Modal";
import { useState } from "react";
import CustomModal from "../components/CustomModal";

export default function Home() {
	const [open, setOpen] = useState(false);
	const handleOpen = () => setOpen(true);
	const handleClose = () => setOpen(false);

	return (
		<div className="bg-gray-100">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar handleOpen={handleOpen} />
			<main className="container bg-gray-100 mx-auto">
				<HeroTwo handleOpen={handleOpen} />
				{/* <Hero /> */}
				<CustomModal
					open={open}
					setOpen={setOpen}
					handleClose={handleClose}
					handleOpen={handleOpen}
				/>
				<Collage />
			</main>
		</div>
	);
}
